# fly.toml app configuration file generated for amarchat on 2024-01-26T16:51:18Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "amarchat"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
